### ISSUE TITLE
Add video instructions for setting up an Phantom wallet

### ISSUE THREAD

**Issue by VIKOLO** [srcfl/srcful-documentation#11]
https://docs.srcful.io/getting-started/setting-up

Maby we can add/link an video already available on Youtube for setting up a Phantom wallet?

**Comment by VIKOLO** [comment]
https://www.youtube.com/watch?v=CoyvAyxX0aw

**Comment by FranzThor** [comment]
I think I got some time this week to make a video on this. Requires basically no prep, and having watched the video, I believe I could make it a bit shorter. More content on our Youtube drives traffic our way.
