### ISSUE TITLE
Invite Companies to build services:

### ISSUE THREAD

**Issue by VIKOLO** [srcfl/srcful-documentation#5]
Add a title and a description to our docs or website. I'm thinking something like:
Our ambition is to build the world's largest decentralized virtual power plant together, where we connect solar panels and home batteries to be able to read data and control in real-time. Do you have services that suit our members? 

Contact us at sales@srcful.io, and we'll schedule a meeting.

**Comment by FranzThor** [comment]
In the documentation, would we want to have this on the immidiate landing page, or put it in "Srcful Simplified", or create a new section altogether, say "Partnership"?

**Comment by VIKOLO** [comment]
Landing page✅

**Comment by FranzThor** [comment]
On it!

**Comment by FranzThor** [comment]
I rewrote it a little bit: 
"Our ambition is to lead the development of the world's largest decentralized virtual power plant. By integrating solar panels and home batteries, our aim is to facilitate real-time data monitoring and control, thereby transforming energy management on a global scale."

If you think that's fine, we can close this issue. :)

**Comment by VIKOLO** [comment]
Great, that's fine!
